### ISSUE TITLE
Conference-specific logo from Fixate

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/conference-planning-2024#15]
Logo specific to South Africa conference.

**Comment by mphilbrick211** [comment]
Due Date is placeholder.

**Comment by cassiezamparini** [comment]
Hi @mphilbrick211 I think Ali and I can't be assigned as we don't have the permissions. Maybe it's a good idea to give us the right access so you can assign us where needed? I see you can assign multiple users to issues.

- https://docs.github.com/en/get-started/learning-about-github/access-permissions-on-github
- https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users

On another note, I'm going to start looking into this from Wednesday this week. I'll be in touch later next week with some initial concepts. Let me know if you guys have any specific requests? Or can we just do our thing? 🚀

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini!

- I'm checking with Ed on the permissions item (I'm not sure I have the admin rights to add you)
- Sounds good about the logo - I don't think there's any specific requests - just do your thing! You're already familiar with our brand colors, logos, etc. Let me know if there's anything you need.

**Comment by cassiezamparini** [comment]
@mphilbrick211 Ed has given me permissions. So I've assigned myself to this issue.

**Comment by mphilbrick211** [comment]
@cassiezamparini hey there! Just checking in to see how things are going - do you still plan for some concept work to be ready by the end of the week?

**Comment by cassiezamparini** [comment]
Hi @mphilbrick211 that's still the plan 😄 I'll update you if anything changes

**Comment by cassiezamparini** [comment]
Hi @mphilbrick211 Below is a presentation of the proposed "logo" design. We received so much good feedback last year that I decided to base it off that winning formula 😄  but with a twist. Because the stickers were such a hit last year, I thought why not make a sticker series? South Africa is such an abundant and diverse country, and while Stellenbosch and Cape Town are only 30 - 45 mins away by car, the scenery is beautifully different. SO, to cut a long story short, there are 3 sticker designs, showcasing three different views of the Cape. The idea is that the logos can be used in different places across the conference branding, and attendees get a few sticker designs to choose from 😄 

Looking forward to your feedback!
 
[Logos 2024 - Presentation.pdf](https://github.com/openedx/conference-planning-2024/files/13393840/Logos.2024.-.Presentation.pdf)

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini! We definitely want to go with these two - can you send them to us in all the formats we'll likely need so we can start using them?

As for a third one, we're open to still having 3 logos. It looks like you had a few ideas on what you could use for it - maybe we try this one? _"The rolling hills and perhaps a protea and sugar bird - very typical to the Cape"_

![Image](https://github.com/openedx/conference-planning-2024/assets/100873803/a3b54d5d-804f-4f98-9f48-6b713c06c693)

**Comment by cassiezamparini** [comment]
Excellent @mphilbrick211 😄 

I've uploaded the RGB logos for now - these are just for web use. Will you need CMYK, print ready logos, any time soon?

On another note, to confirm, you don't like this logo with the colorful houses (Bokaap) in Cape Town? Would you prefer something more "nature driven"?

![3rd logo](https://github.com/openedx/conference-planning-2024/assets/10086170/3f1bf512-899b-4de6-b308-e8e8fa0c09c3)

cc. @e0d 

Here are the vector and PNG versions of the logos:
[logo-cape-town-vector-web.pdf](https://github.com/openedx/conference-planning-2024/files/13512725/logo-cape-town-vector-web.pdf)
[logo-stellenbosch-vector-web.pdf](https://github.com/openedx/conference-planning-2024/files/13512728/logo-stellenbosch-vector-web.pdf)
![logo-cape-town-web](https://github.com/openedx/conference-planning-2024/assets/10086170/9d6c0f13-5d56-401b-9385-ae7a9a1ee96c)
![logo-stellenbosch-web](https://github.com/openedx/conference-planning-2024/assets/10086170/0d1310c5-75c9-415d-b87f-00ef5e2904c4)

**Comment by mphilbrick211** [comment]
@cassiezamparini so I made a mistake. This one with the colorful buildings is OK. 

![Image](https://github.com/openedx/conference-planning-2024/assets/100873803/7d9e84bd-27d0-44c9-9858-2eacd1f137d7)

**This one below with the single building is **_not_**. The local org we're working with on the conference thought it was evocative of colonialism.** 

![Image](https://github.com/openedx/conference-planning-2024/assets/100873803/3ff7e7a4-2797-492d-a4eb-46ca3c69b9db)

--------------
So, we need all file types (web and print-ready) of these two, and a third more focused on nature as you mentioned.


![Image](https://github.com/openedx/conference-planning-2024/assets/100873803/d59d49ca-bf7d-4ac8-a48c-60c61c5cfc4c)

![Image](https://github.com/openedx/conference-planning-2024/assets/100873803/3f41ad36-1187-451d-99a1-8401d4a7f1fa)

Apologies for the confusion.

**Comment by cassiezamparini** [comment]
Okay @mphilbrick211 I thought you might have gotten new feedback on it! Okay cool, let me save the colorful buildings one. Then we can tweak the Stellenbosch one in time. I know Ed said we should wait on it, but we could come up with an appropriate replacement sooner rather than later?

**Comment by e0d** [comment]
No need to wait if you have a new concept.

**Comment by cassiezamparini** [comment]
@mphilbrick211 Here is the 2nd logo. I'm getting to work on the Stellenbosch logo update :) 

[logo-bokaap-vector-web.pdf](https://github.com/openedx/conference-planning-2024/files/13523652/logo-bokaap-vector-web.pdf)
![logo-bokaap-web](https://github.com/openedx/conference-planning-2024/assets/10086170/a90faafb-31bf-414e-a907-cf5746f36eb6)

**Comment by cassiezamparini** [comment]
@e0d  @mphilbrick211 Here's a 3rd logo option. The building is based on the university buildings in Stellenbosch, with their typical red roofs. See what you think:

![Stellenbosch option](https://github.com/openedx/conference-planning-2024/assets/10086170/5ee7eb0f-67b4-49dd-827b-033ace88218c)

**Comment by cassiezamparini** [comment]
@e0d and @mphilbrick211 just a reminder, I'll be on leave from the 8th December 2023 until the 3rd of January 2024 :) But I think we have everything handled for now?

**Comment by mphilbrick211** [comment]
Thanks, @cassiezamparini! Quick question - the colors in this one look different, almost like muted versions of the color palette - just want to confirm that the final would have the same coloring as the others?

**Comment by mphilbrick211** [comment]
> @e0d and @mphilbrick211 just a reminder, I'll be on leave from the 8th December 2023 until the 3rd of January 2024 :) But I think we have everything handled for now?

@cassiezamparini I think we should be all set, barring any additional feedback on the 3rd logo, but as we already have the other 2 I think we're OK in the meantime.

**Comment by mphilbrick211** [comment]
> Thanks, @cassiezamparini! Quick question - the colors in this one look different, almost like muted versions of the color palette - just want to confirm that the final would have the same coloring as the others?

Hi @cassiezamparini! I hope you had a great holiday break! I'm bumping this for when you return. For the third logo:

- As mentioned above, the colors seem off on this one, almost like a different contrast and not as vibrant?
-  Would we be able to see a version of it with blue sky?

**Comment by cassiezamparini** [comment]
@mphilbrick211 Wishing you a Happy 2024! I'm looking at this now ;) will be in touch soon.

**Comment by cassiezamparini** [comment]
@mphilbrick211 I'm not sure what happened but the color codes slightly changed on all three logos - not just the one. I'm sorry about that - it's a mystery really. So I've had to redo them. See the correct colors below and let me know your thoughts (I've changed the sky on two of them, so that each one has a different sky color):

![Logos-colors-adjusted](https://github.com/openedx/conference-planning-2024/assets/10086170/770338c6-047c-4672-9b10-ab1380809ce5)

Where have the logos been used other than on the social ads?

**Comment by cassiezamparini** [comment]
> @mphilbrick211 I'm not sure what happened but the color codes slightly changed on all three logos - not just the one. I'm sorry about that - it's a mystery really. So I've had to redo them. See the correct colors below and let me know your thoughts (I've changed the sky on two of them, so that each one has a different sky color):
> 
> ![Logos-colors-adjusted](https://private-user-images.githubusercontent.com/10086170/293929229-770338c6-047c-4672-9b10-ab1380809ce5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODk5MDEsIm5iZiI6MTcwNDg4OTYwMSwicGF0aCI6Ii8xMDA4NjE3MC8yOTM5MjkyMjktNzcwMzM4YzYtMDQ3Yy00NjcyLTliMTAtYWIxMzgwODA5Y2U1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEyMjY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMmNkZGVhYjY0YTRkZWYyMDM2MmUwMjg4MTAwNDNlNWI4OGM4MjU4MTVkODA1N2I4ZmI0MzJkYmM1ZjdlMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9FoDXzjbGb227kniCNl_Y6iEP2-UXey-S_Fom-3QoQ)
> 
> Where have the logos been used other than on the social ads?

Hi @mphilbrick211 and @e0d just pinging you on the above comment :)

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini - the planning team is meeting right now, we should have some feedback ASAP!

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini! These are great! Could we get all 3 in all the file formats (high-res, etc.)?

**Comment by cassiezamparini** [comment]
@mphilbrick211 Perfect, on it.

**Comment by cassiezamparini** [comment]
Hi Michelle,

Here are the RGB Logos (these are for screen):

[Bo-Kaap-Logo.pdf](https://github.com/openedx/conference-planning-2024/files/13937153/Bo-Kaap-Logo.pdf)
[Cape-Town-Ocean-Logo.pdf](https://github.com/openedx/conference-planning-2024/files/13937154/Cape-Town-Ocean-Logo.pdf)
[Stellenbosch-logo.pdf](https://github.com/openedx/conference-planning-2024/files/13937155/Stellenbosch-logo.pdf)
![Bo-Kaap-Logo](https://github.com/openedx/conference-planning-2024/assets/10086170/646b22d9-1bb9-40f8-9006-3ca5416bd8a6)
![Cape-Town-Ocean-Logo](https://github.com/openedx/conference-planning-2024/assets/10086170/deb6c18a-4000-4e1b-9f2d-d5b4ecbf4644)
![Stellenbosch-logo](https://github.com/openedx/conference-planning-2024/assets/10086170/6894dec2-6650-43d4-8b0a-de0d4c1b9a02)

**Comment by cassiezamparini** [comment]
Below are the logos to use for print work (their colors will look a bit odd on screen but they are the correct CMYK values according to your brand guidelines):

[Bo-Kaap-Logo-CMYK.pdf](https://github.com/openedx/conference-planning-2024/files/13937873/Bo-Kaap-Logo-CMYK.pdf)
[Cape-Town-Ocean-Logo-CMYK.pdf](https://github.com/openedx/conference-planning-2024/files/13937874/Cape-Town-Ocean-Logo-CMYK.pdf)
[Stellenbosch-logo-CMYK.pdf](https://github.com/openedx/conference-planning-2024/files/13937875/Stellenbosch-logo-CMYK.pdf)

![Bo-Kaap-Logo-CMYK](https://github.com/openedx/conference-planning-2024/assets/10086170/e94215a5-0911-493a-a181-29d7b3e1b610)
![Cape-Town-Ocean-Logo-CMYK](https://github.com/openedx/conference-planning-2024/assets/10086170/e379b192-f331-4698-b4ea-4e298d1f3d50)
![Stellenbosch-logo-CMYK](https://github.com/openedx/conference-planning-2024/assets/10086170/4dfe743a-6d66-40d9-9519-79b28a30a4b6)
