### ISSUE TITLE
Add speakers to Salesforce so we can use email campaigns and docusign forms for releases, etc.

### ISSUE THREAD

**Issue by e0d** [openedx/conference-planning-2024#38]
Add speakers to Salesforce so we can use email campaigns and docusign forms for releases, etc.

**Comment by mphilbrick211** [comment]
@ehuthmacher does this still need to be done?

**Comment by ehuthmacher** [comment]
@mphilbrick211 No, I do not believe so, since Sarina and Feanil are managing the speaker communication via Sessionize
