### ISSUE TITLE
Marketing Assets / Design items (e.g. Imagery for LinkedIn & Google Ad Campaigns)

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/conference-planning-2024#52]

**Comment by cassiezamparini** [comment]
@ehuthmacher Just adding your email correspondence here, so we can keep everything in one place:

> Could you be so kind and create images for me to promote on social media for the 2024 Open edX Conference. We have a LinkedIN, Twitter, and Facebook account. Would you also be able to assist in creating a promotional conference video, similar to [this one ](https://www.youtube.com/watch?v=kHkypSzbKBs)for Stellenbosch?

- We can absolutely create the social media images (like we did last year). But should we wait until we have completed the Conference logo? I know we used the logo in the designs for our 2023 social media campaigns.

- We don't offer promotional video services, but I know we sent you a contact last year. Would you like me to send their details again?

cc. @mphilbrick211

**Comment by cassiezamparini** [comment]
@ehuthmacher I'm ready to start work on the social ads now that the first two logos are approved 😄 

Just to confirm scope, will you need:

1. LinkedIn Event Image (Event logo size: 300 x 300 - square and event ‘banner’ size: 1600 x 900 pixels)
2. Google Ads ([Here's an article](https://growthmindedmarketing.com/blog/google-display-ads-sizes/) indicating the top performing Google Ad sizes - will you let me know which size you would like?)
3. Let me know if you need anything else?

@mphilbrick211 Should we use this logo for the social media campaigns:
![logo](https://github.com/openedx/conference-planning-2024/assets/10086170/9944057a-b33d-442e-91dd-6759c6dbede2)

**Comment by mphilbrick211** [comment]
@cassiezamparini that one looks great! Though, I will defer to @ehuthmacher to make the final call as she'll be doing the posts.

**Comment by ehuthmacher** [comment]
@cassiezamparini The image that @mphilbrick211 selected for the social media campaigns looks good to me. And yes, I will need LinkedIn Event Image (Event logo size: 300 x 300 - square and event ‘banner’ size: 1600 x 900 pixels) and a Google Ads image (300x250). Thank you!!

**Comment by cassiezamparini** [comment]
@ehuthmacher I was looking at the LinkedIn Event pages, and I'm not sure where the 300 x 300 event logo is placed? See example page: https://www.linkedin.com/events/7135391864844689408/about. Can you share a reference? I need to see if the logo is shown as a square or in a circle.

In the meantime, here is the Google ad design:
![open-edx-2024-google-ad](https://github.com/openedx/conference-planning-2024/assets/10086170/c23c028d-4313-4e56-a463-460cd00eccbc)

And two options for the LinkedIn Event banner:
![open-edx-2024-linkedin-ad-1](https://github.com/openedx/conference-planning-2024/assets/10086170/e13ec680-2fa4-4079-b1c4-f0b3ac211ceb)
![open-edx-2024-linkedin-ad-2](https://github.com/openedx/conference-planning-2024/assets/10086170/9678b1e8-accd-44c1-9a83-2be30b44eecd)

Please let me know your thoughts :)

**Comment by mphilbrick211** [comment]
@cassiezamparini I know I'm not Eden, but just popping in to say those look great! One question (probably for @ehuthmacher) are we not including the location in these?

**Comment by cassiezamparini** [comment]
Good point @mphilbrick211. There isn't much space on the Google Ad though.

**Comment by ehuthmacher** [comment]
@cassiezamparini @mphilbrick211 I agree, those images look great! Including the location would be great, if possible.Regarding the LinkedIn event logo, it should be a square image size 300x300, when I checked the instructions. We have not created the event page yet.

**Comment by cassiezamparini** [comment]
Hi @ehuthmacher here are the updated images ready for use. I've included 3 x 300 by 300 logos, so you can see what works best. I think perhaps the plain logo will work well (without the "2024").

![google-ad-open-edx-2024](https://github.com/openedx/conference-planning-2024/assets/10086170/88c5eb5f-79e2-4e1d-ba88-3361dcb0906d)
![linkedin-event-banner-1](https://github.com/openedx/conference-planning-2024/assets/10086170/e44a5e4b-692a-4225-8b24-044a05826cb1)
![linkedin-event-banner-2](https://github.com/openedx/conference-planning-2024/assets/10086170/2687dab1-30c7-47a9-bab3-52af6496be44)
![logo-1](https://github.com/openedx/conference-planning-2024/assets/10086170/780232e0-38d1-45bc-a487-26df6fcd7a37)
![logo-2](https://github.com/openedx/conference-planning-2024/assets/10086170/c90915f2-a798-47bb-8608-3d2bec43df34)
![logo-3](https://github.com/openedx/conference-planning-2024/assets/10086170/de17430d-5eaf-4a8c-bfe5-f690f1998d6e)

**Comment by ehuthmacher** [comment]
@cassiezamparini Great, thank you!

**Comment by ehuthmacher** [comment]
@cassiezamparini Somehow the images came up blurry on LinkedIn. I had to use a different image, you can view the event here: https://www.linkedin.com/events/openedxconference20247137797985953804288/about/

.

**Comment by cassiezamparini** [comment]
@ehuthmacher Try the jpeg format below, and let me know...

![linkedin-event-image](https://github.com/openedx/conference-planning-2024/assets/10086170/9310f1c7-b291-4fb4-8f74-ebeee1305daf)

**Comment by ehuthmacher** [comment]
@cassiezamparini Could you kindly email me the jpeg file? I am not able to download it as a jpeg in GH.

**Comment by ehuthmacher** [comment]
@cassiezamparini NVM, I was able to download the image and updated it successfully. It looks great: https://www.linkedin.com/events/openedxconference20247137797985953804288/comments/

**Comment by cassiezamparini** [comment]
@ehuthmacher Amazing! So can we mark this issue as "done"?

**Comment by ehuthmacher** [comment]
@cassiezamparini Yes, thank you!
