### ISSUE TITLE
Consider discounted tickets for Speakers

### ISSUE THREAD

**Issue by e0d** [openedx/conference-planning-2024#55]
The planning team will each research one of the following conference and report back.  We'll use this to establish what a reasonable norm would be.

What we want to understand what these conferences do to support accepted speakers attend, if anything.

1. EMOOCs
2. Learning@Scale
3. Pycon
4. EduCause
5. OEB Global
6. OSCon - No longer active but when it was, it gave speakers complimentary tickets.

**Comment by ehuthmacher** [comment]
I'll look into OEB Global

**Comment by mphilbrick211** [comment]
From EduCause's 2023 CFP: https://events.educause.edu/annual-conference/call-for-proposals

<img width="735" alt="Screenshot 2023-11-07 at 2 40 09 PM" src="https://github.com/openedx/conference-planning-2024/assets/100873803/d91671bf-c263-4e13-acd0-d3ad13f123b2">

**Comment by sarina** [comment]
I'll take Pycon

**Comment by e0d** [comment]
Neither EMOOCs, nor IEEE LWMOOCs offered discounts for speakers with accepted talks.  Invited speakers were given passes.

**Comment by sarina** [comment]
Pycon does not offer discounts or free tickets for speakers, however they have an application process for travel grants:

> PyCon US does not want expenses to discourage you from submitting a proposal and speaker travel grants ensure that if assistance is needed and your proposal is accepted you can speak at PyCon US. When you create a speaker profile, check the box to indicate that you require a speaker grant. This is not seen by the proposal reviewers and does not affect the review of your proposal.

It does not say anywhere how big the grants are or how much they might cover.

**Comment by ehuthmacher** [comment]
At OEB Global they only offer speaker's package combined to the sponsor's package. You cannot register as speakers only, therefore the discounts are the following:
50% discount for universities member, researchers, or students
30% discount for corporate members

**Comment by mphilbrick211** [comment]
11/17 - decision to keep prices same for speakers, but add a clause that we can assist with financing where appropriate (if there are barriers for attending without support). @ehuthmacher

**Comment by ehuthmacher** [comment]
@mphilbrick211 Yes, I will add the clause to the CFP blog and the conference website.

**Comment by ehuthmacher** [comment]
@mphilbrick211 @e0d I have added the proposed changes to the CFP blog & website: https://con.openedx.org/
