### ISSUE TITLE
Determine deadline for Sponsor Asset Collection

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/conference-planning-2024#58]
Need to know when the deadline to collect sponsor assets is for material printing

**Comment by ehuthmacher** [comment]
@cassiezamparini Could you kindly inform me when you need all of the sponsor assets by?

**Comment by cassiezamparini** [comment]
Hi @ehuthmacher, there is no rush on this, I'm sure we'll only tackle the banners, program etc in 2024. 

My aim is to have the logo finalised and get the social ads done before year end. What do you think @mphilbrick211?

PS: I am going on leave from the 11th December for our South African summer holidays.

**Comment by mphilbrick211** [comment]
sounds good to me, @cassiezamparini!
