### ISSUE TITLE
Explore Interactive Conference Apps

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/conference-planning-2024#60]
We need an interactive conference app that allows the audience to connect directly with our speakers, as well as rate their sessions. Kindly add your suggestions here

**Comment by mphilbrick211** [comment]
11/29/23 - Eden demoed [PINE](https://pine.events/)

- can import information from Sessionize
- imports registration info from Eventbrite
- includes chat features both session-specific and event-wide / support channel
- recordings can be uploaded
- information can still be accessed after the event (weeks, years, etc)
- allows sponsors to have virtual exhibitions with their own demos and videos (for an extra charge)
- can show all the orgs represented at the conference
- allows for slides to be shared on the app (though this can also be done in sessions)
- people can schedule meetings with other attendees
- people can customize schedule

$3 per active attendee during the conference (paid after the conference). The sponsor exhibition is $100 extra per company.

**Comment by ehuthmacher** [comment]
Link to test the pine platform: https://app.pine.events/attendee/events/2930/overview

**Comment by mphilbrick211** [comment]
Southern Cross has had great experience with [EventMobi](https://www.eventmobi.com/). It's a conference app and streaming platform (similar to Pine).

12/14 - MP sent an email requesting Zelda and Gwynneth be added to demo of Pine.

**Comment by ehuthmacher** [comment]
@mphilbrick211 That's great, thank you! Will they provide us with a demo of [EventMobi](https://www.eventmobi.com/) ?

**Comment by mphilbrick211** [comment]
Just confirming here that we're using EventMobi. Contract in-progress.
