### ISSUE TITLE
Integrate Session Target Audience

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/conference-planning-2024#61]
We need to identify the target audience for each presentation and integrate this data into the conference schedule. Kindly determine a mechanism for tracking this information in advance.

**Comment by feanil** [comment]
@ehuthmacher can you provide some more guidance on what you believe the values for target audience would be?  I don't understand if you want more detailed data within any given track or if there is some orthogonal metric that you want to capture/make visible.

**Comment by ehuthmacher** [comment]
@feanil We received feedback in the post-survey from the audience last year that sessions were not properly identified, in terms of target audience. The audience wants to know if a given session requires technical background, as well as any pre-knowledge. 

For example, one of the organizers of the next Open edX meetup, included this phrase, in terms of target audience: "Whether you're an experienced Open edX user or new to the platform, this presentation will illuminate the benefits of Tahoe's streamlined approach to Open edX hosting."

If you integrate a required question for the speakers to complete, related to the target audience and knowledge required, we can sync the information over to the schedule and the audience can better define which sessions match their knowledge base.

**Comment by feanil** [comment]
got it, I think I understand, I'll add an open-ended question about who the target audience should be along with some guidance like:

> Who is the target audience?

> What level of technical experience do they need? What do you expect them to already know.

**Comment by ehuthmacher** [comment]
Yes, that would be great, thank you @feanil !

**Comment by feanil** [comment]
This is done.
