### ISSUE TITLE
2024 Open edX Conference Sponsor Deck

### ISSUE THREAD

**Issue by cassiezamparini** [openedx/conference-planning-2024#65]
This issue is to review the 2024 Open edX Conference Sponsor Deck.

[View the presentation here.](https://docs.google.com/presentation/d/1u7IcGRoUfkcKNJ116p2BbkqwAAF0QU8UFxRdBmPZ23Y/edit?usp=sharing)

**Comment by cassiezamparini** [comment]
@ehuthmacher I've opened this ticket for the slide deck review 😄  I've made some changes to the text (just let me know if you don't agree), and slide order. I've also left you one or two comments.

[View the presentation here.](https://docs.google.com/presentation/d/1u7IcGRoUfkcKNJ116p2BbkqwAAF0QU8UFxRdBmPZ23Y/edit?usp=sharing)

**Comment by ehuthmacher** [comment]
@cassiezamparini The deck looks great, thank you for all of your efforts. Could you kindly make the following two edits:
1. Corporate rate is $699 not &499
2. Sponsorship pricing in ZAR is currently marked as X. Could you kindly add in the following rounded values? 
Reception - 658,000
Cornerstone - 470,000
Premier - 282,000
Keystone - 189,000
Contributing - 94,000
Friend - 38,000
In-kind - 0.00

Thank you in advance!

**Comment by cassiezamparini** [comment]
@ehuthmacher Done :) https://docs.google.com/presentation/d/1u7IcGRoUfkcKNJ116p2BbkqwAAF0QU8UFxRdBmPZ23Y/edit#slide=id.p

We just need Sarina's photo. 

I'm on leave next Mon and Tues, do you think you can get the image to me today and then I'll slot it in tomorrow my time?

**Comment by ehuthmacher** [comment]
Thank you @cassiezamparini ! Sarina indicated that she emailed her photo to you. Did you receive it?

**Comment by cassiezamparini** [comment]
@ehuthmacher Sorted! [Ready for you to share](https://docs.google.com/presentation/d/1u7IcGRoUfkcKNJ116p2BbkqwAAF0QU8UFxRdBmPZ23Y/edit?usp=sharing). Here's a PDF of the presentation as well:
[2024 Open edX Conference Sponsor Deck.pdf](https://github.com/openedx/conference-planning-2024/files/14382561/2024.Open.edX.Conference.Sponsor.Deck.pdf)

😄

**Comment by ehuthmacher** [comment]
Perfect, thank you so much!! :)
