### ISSUE TITLE
Learning Technologies Stand Design

### ISSUE THREAD

**Issue by cassiezamparini** [openedx/conference-planning-2024#66]
### Create an Open edX stand wall design:

<img width="123" alt="Screenshot 2024-02-22 at 16 18 08" src="https://github.com/openedx/conference-planning-2024/assets/10086170/d470210c-5df8-4f78-91c6-b2f9b540f6da">

---
- [Stand dieline](https://github.com/openedx/conference-planning-2024/files/14375082/Moyne.2m.x.2m.pdf)
- Integrate elements of the USP:

<img width="571" alt="Screenshot 2024-02-22 at 16 21 13" src="https://github.com/openedx/conference-planning-2024/assets/10086170/ca8f07e3-e1ab-4866-9656-80ad109191ab">

**Comment by cassiezamparini** [comment]
@ehuthmacher I'm away next Monday and Tuesday so @ali-hugo has said she'd be able to assign some of her Core Contributor hours to this  😄 

Will you check if everything in the description is correct? And then I have a few more questions:

- Is this a general marketing stand to sell the Open edX Platform? ie. This isn't 2024 conference related?
- Is there any parts of the USP in particular that you'd like us to include?

Let me know if there are any other specific requests you have for the design!

cc. @ali-hugo

**Comment by ehuthmacher** [comment]
@cassiezamparini @ali-hugo Thank you for your support, I appreciate it! Regarding your questions, pleasesee my answers below:
1. It is just a general marketing stand to sell the Open edX Platform and not related to the 2024 conference. 
2. I am wondering if we can fit both pages onto the wall panels, since there are two panels. If not, the first page broken up 
[Uploading USP - LWMOOCs.pdf…]()
would be fine. 
Let me know if you have any other questions and thank you again for your support!

**Comment by ali-hugo** [comment]
@ehuthmacher Thanks for the additional information. I'm on it!

I would like to run the design by Cassie when she's back from leave later this week. Would that be ok, or do you need the design urgently?

**Comment by ehuthmacher** [comment]
@ali-hugo Sure, that is fine. The artwork is due on April 1st, so we have some time. Thank you for checking in!

**Comment by cassiezamparini** [comment]
@ehuthmacher Here's a mock-up of the stand design. We've changed the text (shortened) and layout a bit so the design is a bit more "punchy". Please review the text and let me know what you think, or if we should change anything.

Looking forward to your feedback!

![Learning Technologies Stand](https://github.com/openedx/conference-planning-2024/assets/10086170/c2aadb36-00a4-40a6-a709-d6502cd9296e)

**Comment by ehuthmacher** [comment]
@cassiezamparini Thank you! I was informed by the organizer that the text should be minimal. They sent me the attached guidelines. Let me know your thoughts. 
![artwork - Learningtech](https://github.com/openedx/conference-planning-2024/assets/79525573/a7e9ad86-34e9-48ee-8349-387a2691f810)

**Comment by cassiezamparini** [comment]
@ehuthmacher Okay cool :) 

We could do a similar vibe to the roll up banner we did.
<img width="352" alt="Screenshot 2024-03-04 at 08 20 10" src="https://github.com/openedx/conference-planning-2024/assets/10086170/b4168ba4-de5a-4b7d-9dc2-6aa895cadcb3">

They say one single image over a large area is the most impactful and key messaging should be on the gangway walls (makes sense). So let me know if:

1. What key messages you'd like me to include?
2. If there are any particular images I should use, or can I make this call?

**Comment by ehuthmacher** [comment]
@cassiezamparini Yes, that would be great! We would just need to erase the co-sponsor section and you can include the following message in large font:

The Open edX LMS: Innovative. Robust. Scalable.

Could you kindly at this message at the top, followed by the existing information below it?

Regarding the images, I will leave it to your discretion. :)

Thank you again!!

**Comment by cassiezamparini** [comment]
@ehuthmacher I've simplified it a lot so it's much more bold and punchy. What do you think?

<img width="1243" alt="Simpler-design" src="https://github.com/openedx/conference-planning-2024/assets/10086170/8e351a73-5eb3-435b-95ac-43a56350894f">

**Comment by ehuthmacher** [comment]
@cassiezamparini That looks great to me, thank you! Could you kindly send me the file to share with the conference asset team?

**Comment by ehuthmacher** [comment]
@cassiezamparini @ali-hugo Just a kind reminder, could you kindly send me the file to share with the Learning Tech team?

**Comment by cassiezamparini** [comment]
@ehuthmacher [Here's a link to the file](https://www.dropbox.com/s/j5w89pai9wv4ub8/Learning%20Technologies%20Stand.pdf?dl=0) :)

**Comment by ehuthmacher** [comment]
@cassiezamparini Thank you!

**Comment by cassiezamparini** [comment]
@ehuthmacher Let me know if you have any final changes :) I'll keep this issue open until I hear back from you.

**Comment by ehuthmacher** [comment]
Will do, thank you @cassiezamparini !

**Comment by ehuthmacher** [comment]
@cassiezamparini This is the feedback I received: 

1. Template for the tension fabric which runs round the 2 inner 2m walls. **You require one additional piece of artwork for the rear of your 2m back wall to the same 2m size of 1940mm x 2370mm – I have 2 pieces the side and front of the back wall but not the reverse of the back wall**

2. When designing artwork please factor in the position of the TV allowing for the TV size of 1060mm wide x 625mm high. Please indicate on the artwork or via a plan the required position of the TV / TV Panel

Could you kindly assist with this?

**Comment by ehuthmacher** [comment]
@cassiezamparini Sorry, they are also saying that we need a Fascia Overlay design,  covering our nameboard structure – All the same design 1 @ 5000mm x 300mm 1 @ 2000mm x 300mm 1 @ 5000mm x 300mm

**Comment by cassiezamparini** [comment]
Absolutely @ehuthmacher 

> You require one additional piece of artwork for the rear of your 2m back wall to the same 2m size of 1940mm x 2370mm – I have 2 pieces the side and front of the back wall but not the reverse of the back wall
Oh goodness - we didn't realise that. What do they suggest here though?
- Should it be a repeat of the inner wall? / Or what should we advertise?
- Will the back of the wall be very visible, or will the other stands be really close to it so not much will be seen?

> When designing artwork please factor in the position of the TV allowing for the TV size of 1060mm wide x 625mm high. Please indicate on the artwork or via a plan the required position of the TV / TV Panel
- Where will the TV be placed? And how will it be placed? Right against the wall?
- Where would you like it positioned for best marketing use?

> Sorry, they are also saying that we need a Fascia Overlay design, covering our nameboard structure – All the same design 1 @ 5000mm x 300mm 1 @ 2000mm x 300mm 1 @ 5000mm x 300mm
- Should we just do a repeating logo like:
<img width="535" alt="Screenshot 2024-03-19 at 13 00 07" src="https://github.com/openedx/conference-planning-2024/assets/10086170/e212a758-29d4-4cf7-b1c6-0dbd8226b1de">

**Comment by ehuthmacher** [comment]
Thank you @cassiezamparini ! Please see the answers to your questions below:

- Should it be a repeat of the inner wall? / Or what should we advertise? - **Yes, a repeat of the inner wall is fine** 
- Will the back of the wall be very visible, or will the other stands be really close to it so not much will be seen? - **It will not have much visibility, as the stands are placed in close proximity to each other** 
- Where will the TV be placed? And how will it be placed? Right against the wall?
Where would you like it positioned for best marketing use? **The TV should be centered against the wall/positioned for best visibility, so that people walking by the stand, can see live tutorials an advertisements of the platform**
- Should we just do a repeating logo - **Yes, the repeating logo design looks great. Thank you!**

**Comment by cassiezamparini** [comment]
@ehuthmacher Another question, will the TV be inset or attached to the wall? Or will it stand in front of the wall?

eg:

<img width="780" alt="Screenshot 2024-03-22 at 13 45 36" src="https://github.com/openedx/conference-planning-2024/assets/10086170/58455433-e92e-4f57-8148-55a46bd7fe62">

Do they maybe have any suggestions on the best placement? They would know best. I'm also guessing it should be placed at an average eye height.

<img width="832" alt="Screenshot 2024-03-22 at 14 50 55" src="https://github.com/openedx/conference-planning-2024/assets/10086170/134a1a5b-f20c-4e8b-b9a0-fe6411175b4c">

I'm also thinking the back wall could rather be something like this (I see a few stands do this sort of thing). It's a nice bold contrast from the "inside" panels. The color might catch people's eyes:

<img width="830" alt="Screenshot 2024-03-22 at 14 52 36" src="https://github.com/openedx/conference-planning-2024/assets/10086170/b7ee181c-6c38-41d5-87c9-2b6b3b26d9fc">


And the fascia overlay:
<img width="1504" alt="Screenshot 2024-03-22 at 14 54 05" src="https://github.com/openedx/conference-planning-2024/assets/10086170/98ddd977-d71b-4f15-b9c2-284f76a04f7a">


Let me know your thoughts :)

**Comment by ehuthmacher** [comment]
Thank you @cassiezamparini ! All of your suggestions look great so far, thank you! Regarding the TV, we decide where to place it and the artwork should indicate which panel / the location of the TV (see guideline attached). 
[46 inch TV Installation & Artwork Guide.pdf](https://github.com/openedx/conference-planning-2024/files/14743511/46.inch.TV.Installation.Artwork.Guide.pdf)

I added 2 x panels – I was thinking that the TV could go 2 meters to the back wall on one of the panels? It must either be the left or the right panel of the 2 (not in the center), according to the instructions. I think eye level of slightly above eye level would be great.

Please let me know if you have any other questions. Thanks again!!

**Comment by cassiezamparini** [comment]
@ehuthmacher Oh that document with the TV specs helps heaps! On it :)

**Comment by ehuthmacher** [comment]
Thank you @cassiezamparini !!

**Comment by cassiezamparini** [comment]
Hi @ehuthmacher

[Here is a link](https://www.dropbox.com/scl/fo/dy8cf63qd6u0xcrlxhv3t/AN9Do3wZzTesMfwvskhVpzw?rlkey=4pdlw2sua7x2jv80kpmcpqtba&dl=0) to the files.

The file called "Print files - Learning Technologies Stand.pdf" includes all the print ready pieces for the stand. 
And the file called "TV-Placement--Learning-Technologies-Stand.jpg" shows the TV location.

Let me know if all looks good to go! :)
