### ISSUE TITLE
Conference Website Updates

### ISSUE THREAD

**Issue by cassiezamparini** [openedx/conference-planning-2024#71]
Make the following updates to [con.openedx.org](http://con.openedx.org/):

- Add the [Sessionize](https://f7fe99e3792b41578028010366ee0d55.sessionize.com/schedule) program to the website
- Tweak website design to adhere to current Conference brand look-and-feel

**Comment by cassiezamparini** [comment]
@ehuthmacher I only have access to https://openedx.org/wp-admin/

Could you give cassie@opencraft.com access to **https://con.openedx.org/wp-login.php**? Then I can start the conference website updates 😄 

cc. @mphilbrick211

**Comment by mphilbrick211** [comment]
@cassiezamparini - Eden is traveling this week - @e0d is this something you can help with?

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini - can you try again? I think Ed updated your permissions. Let us know if it works!

**Comment by cassiezamparini** [comment]
@mphilbrick211 Just logged in successfully! Thank you to you and @e0d 

I'll keep you posted 😄

**Comment by cassiezamparini** [comment]
@e0d is there a way for me to change the link color globally - I see I don't have permissions to changing the global link appearances etc for some reason. Or is there anyone who can assist me with this?

cc. @mphilbrick211

**Comment by cassiezamparini** [comment]
@mphilbrick211 @e0d @ehuthmacher 

Hi guys,

I'm ready to embed the sessionize program on the conference site, but first need the embed link 😄  You're welcome to give me access to Sessionize so I can find it, alternatively you can send it to me. [Here's how you find it on Sessionize](https://sessionize.com/playbook/wordpress-embedding).

I've made some styling updates to the conference website to match the conference branding. And just make it easier to consume the information: https://con.openedx.org

@e0d I made some CSS updates to the link text, but this doesn't show correctly on the live site. Who can assist me with this? As I see I don't have permissions to make global updates to the color palette. 

Links should look like this:


![Image](https://github.com/openedx/conference-planning-2024/assets/10086170/c6c47aea-74fc-4c3b-8ef1-e77d3c16f9c6)


But instead show up like this:
![Image](https://github.com/openedx/conference-planning-2024/assets/10086170/2fd41860-b005-4a2f-b0c9-6d2750b373f9)

**Comment by mphilbrick211** [comment]
@cassiezamparini - we're looking at the link issue internally, but it's not a blocker - OK to post the update

**Comment by cassiezamparini** [comment]
@mphilbrick211 Awesome!

I think the major thing now is adding the Sessionize program. Can you assist with this Michelle while Eden is away? This and the social ads were our top priority :) 

> I'm ready to embed the sessionize program on the conference site, but first need the embed link 😄 You're welcome to give me access to Sessionize so I can find it, alternatively you can send it to me. [Here's how you find it on Sessionize](https://sessionize.com/playbook/wordpress-embedding).

This is not a blocker either but I've also updated the link style for the main menu but it's still showing up as blue...
<img width="1413" alt="Screenshot 2024-04-24 at 07 00 37" src="https://github.com/openedx/conference-planning-2024/assets/10086170/0bce50ac-6e13-4758-99d3-dba91f513ae5">

**Comment by amirnafees88** [comment]
@cassiezamparini - I fixed the link hover color issue and also provide you access to Add/edit global styles. If you want to add global styles go to Appearance -> Customize -> Additional CSS and make changes there. I also move your CSS for anchor tag here. I also provide you the permission to access the Additional CSS screen.

**Comment by cassiezamparini** [comment]
@amirnafees88 I noticed the change! Thank you for the quick fix and access to the global styles 😄

**Comment by amirnafees88** [comment]
@cassiezamparini Can you also provide the embeded code for Sessionize program that you want to add on the website and where you want to add. Also let me know if you are facing some issue while editing cookie policy page.

**Comment by ehuthmacher** [comment]
@amirnafees88 I created [this ticket](https://trello.com/c/RMHvWdfL/254-add-conference-schedule-to-the-conference-website) in Trello. Could you kindly embed the program on our conference website?

**Comment by amirnafees88** [comment]
@ehuthmacher Sure Let me look into it.

**Comment by amirnafees88** [comment]
@cassiezamparini You can see that the header color issue is also fixed.

<img width="1783" alt="Screenshot 2024-04-24 at 12 39 30 PM" src="https://github.com/openedx/conference-planning-2024/assets/93266196/3dab4994-3300-40e4-a98a-1ee649d3d035">

**Comment by ehuthmacher** [comment]
@feanil Can you provide Cassie with the embed link or access to Sessionize?

**Comment by cassiezamparini** [comment]
@ehuthmacher I'm wondering if the Schedule should go between the Registration info and Location info. What do you think?

![Screenshot 2024-04-24 at 12 18 09](https://github.com/openedx/conference-planning-2024/assets/10086170/95376092-e140-4212-aa52-7cd3749b8608)

**Comment by ehuthmacher** [comment]
@cassiezamparini Yes, right below registration would be great. Thank you!

**Comment by ehuthmacher** [comment]
@cassiezamparini Michelle mentioned that we will highlight the keynote speakers separately from the schedule on the conference website. Will you create a design for the keynote feature on the website as well?

**Comment by cassiezamparini** [comment]
@ehuthmacher 
> Yes, right below registration would be great. Thank you!

Cool, just need the Sessionize embed text before this can be done :)

> Michelle mentioned that we will highlight the keynote speakers separately from the schedule on the conference website. Will you create a design for the keynote feature on the website as well?

Sure thing! Do you have the Keynote information - short bios and photos?

**Comment by ehuthmacher** [comment]
@cassiezamparini Great, thank you. I have pinged @feanil to provide that for you. For the keynote info, I have forwarded you an email with the relevant information. Feel free to reference this[ blog post ](`https://openedx.org/blog/announcing-our-2024-keynote-speakers/`)as well. Thank you for all of your help! :)

**Comment by ehuthmacher** [comment]
Sorry, forgot to add the blog link: https://openedx.org/blog/announcing-our-2024-keynote-speakers/

**Comment by cassiezamparini** [comment]
Sure thing - on it :)

**Comment by ehuthmacher** [comment]
Thank you so much @cassiezamparini !

**Comment by cassiezamparini** [comment]
@ehuthmacher I've added the keynotes to the site, see what you think: https://con.openedx.org/

Perhaps we can shorten the text even more. But you let me know.

**Comment by mphilbrick211** [comment]
@cassiezamparini - Feanil is giving you developer access to Sessionize. That way you can access the different embed codes, and even change the colors to match the rest of the site.

**Comment by mphilbrick211** [comment]
> @ehuthmacher I've added the keynotes to the site, see what you think: https://con.openedx.org/
> 
> Perhaps we can shorten the text even more. But you let me know.

@cassiezamparini - looks good! Though, can we have a heading above them? e.g. "Meet our Keynote Speakers"

**Comment by mphilbrick211** [comment]
> @cassiezamparini - Feanil is giving you developer access to Sessionize. That way you can access the different embed codes, and even change the colors to match the rest of the site.

Direct embed link is here: https://sessionize.com/app/organizer/schedule/api/endpoint/code/13257/11261

**Comment by cassiezamparini** [comment]
> Feanil is giving you developer access to Sessionize. That way you can access the different embed codes, and even change the colors to match the rest of the site.

Thank you @feanil and @mphilbrick211 

> Looks good! Though, can we have a heading above them? e.g. "Meet our Keynote Speakers"

Sure - done :) https://con.openedx.org/

**Comment by cassiezamparini** [comment]
@ehuthmacher and @mphilbrick211 

The sessionize program is embedded. Let me know if you're happy with the way it looks: https://con.openedx.org 😄

**Comment by mphilbrick211** [comment]
> @ehuthmacher and @mphilbrick211
> 
> The sessionize program is embedded. Let me know if you're happy with the way it looks: https://con.openedx.org 😄

Hi @cassiezamparini - I'm not seeing it. Is there a link to it on the main page?

**Comment by ehuthmacher** [comment]
@cassiezamparini The keynote section looks great. Thank you! :) However, I am also not able to see the program in production.

**Comment by cassiezamparini** [comment]
@amirnafees88 Can you assist, or point me in the right direction? 😄  The Sessionize program shows up in Wordpress:

![Screenshot 2024-04-25 at 11 47 07](https://github.com/openedx/conference-planning-2024/assets/10086170/a574bee1-4f9f-4134-aeb3-d69ec2b2b971)

But not on the Live site:
<img width="1317" alt="Screenshot 2024-04-25 at 11 54 12" src="https://github.com/openedx/conference-planning-2024/assets/10086170/d8fef5fa-3a6a-4c93-9618-5fc750dee04c">

Embed (https://con.openedx.org/wp-admin/post.php?post=8&action=elementor):
![Screenshot 2024-04-25 at 11 55 04](https://github.com/openedx/conference-planning-2024/assets/10086170/ba5c1d87-55f8-4783-9afc-aaef81c5188e)

**Comment by amirnafees88** [comment]
@cassiezamparini Let me look into it and get back to you.

**Comment by amirnafees88** [comment]
@cassiezamparini I have to take over the conference home page to edit and you are currently working on it.

**Comment by cassiezamparini** [comment]
@amirnafees88 Okay, I've exited. Thank you!

**Comment by khawaja-awais** [comment]
@cassiezamparini We have resolved the issue, you can verify at your end as well that Sessionize program is showing for all users. We have converted the script that you used into shortcode and implemented it.

**Comment by cassiezamparini** [comment]
@khawaja-awais It works! Thank you so much :)

**Comment by cassiezamparini** [comment]
@ehuthmacher @mphilbrick211 


- Will you check out the schedule now: https://con.openedx.org and let me know :) 
- Also perhaps we need to add: "Schedule" and "Keynote Speakers" to the nav bar:
![Screenshot 2024-04-25 at 12 47 11](https://github.com/openedx/conference-planning-2024/assets/10086170/2e72d221-bece-423c-ace3-83516f94630a)
- The nav is also not very legible when at the top of the site. It might be best to include some sort of background behind the nav
![Screenshot 2024-04-25 at 12 48 41](https://github.com/openedx/conference-planning-2024/assets/10086170/0e24ebe7-1b22-4e9e-806f-7971b70d2a1d)

**Comment by e0d** [comment]
I think the keynotes should be above the main schedule.  I also think we
need a heading and menu item for it.

**Comment by e0d** [comment]
Looks great.  Is it possible to have the timezone default to Cape Town?

Ed.

**Comment by mphilbrick211** [comment]
Agreed, looks awesome @cassiezamparini! Would you be able to add a "Keynotes and schedule" tab at the top right? The other sections have jump links on the top. Just for consistency's sake.

**Comment by cassiezamparini** [comment]
@mphilbrick211 I'm just looking at the navigation. I think we should lose the transparent nav at the top of the site as it makes the nav items illegible (when there's no white background), and we just have a white band at the top.

Then I see FAQs haven't been added to the nav either so I think we should add that in too. It's just that - with 2 - 3 additional items in the nav it's going to get really long. So perhaps we do something like this...

## Option 1
![Screenshot 2024-04-25 at 14 40 50](https://github.com/openedx/conference-planning-2024/assets/10086170/cbd05427-b4e0-48be-be3b-2d6034de8857)

- In this option I've removed "Location"
- Perhaps we can just include the location info in the "About" section?

## Option 2

![Screenshot 2024-04-25 at 14 38 51](https://github.com/openedx/conference-planning-2024/assets/10086170/6c032de2-d923-44f3-9935-ed62c957ce6f)

- I'm guessing Sponsors has to be out in the "open"?

cc. @e0d

**Comment by mphilbrick211** [comment]
Thanks, @cassiezamparini! I think moving up the "location" info to the "about" section makes sense, since it's really just the map. So, I'd prefer option 1 to make things a bit cleaner both for the nav and for the site itself.

Not sure if @e0d has any thoughts.

**Comment by cassiezamparini** [comment]
@khawaja-awais @amirnafees88

Could you assist with the following navigation changes:

![325610823-cbd05427-b4e0-48be-be3b-2d6034de8857-1](https://github.com/openedx/conference-planning-2024/assets/10086170/b9f7c149-8a7e-4e98-8dc2-df95538edd2d)

- Can we keep the main navigation and sticky nav consistent. So both navigations are the same height, and include a white background. I've included a reference above for sizing. 
- Keep the shadow below the sticky nav, but remove it when shown at the top of the site.
- Can you change the nav items to what's shown in the screenshot above: About, Register, Keynotes, Schedule, Travel, FAQs, Sponsors
- Can you remove the underlines from the nav items 

Thank you! I'm on leave this week, so @mphilbrick211 and @ehuthmacher can you sign off on these changes when made? 😄

**Comment by amirnafees88** [comment]
@cassiezamparini Sure. We'll implement these changes and get update you.

**Comment by khawaja-awais** [comment]
Hi @cassiezamparini ,

We have implemented all the changes that you have mentioned above. Kindly review and let us know if anything.

CC: @ehuthmacher @mphilbrick211

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini @amirnafees88 @khawaja-awais! This looks fantastic, thank you!
