### ISSUE TITLE
Conference Printed Program 

### ISSUE THREAD

**Issue by cassiezamparini** [openedx/conference-planning-2024#72]
### Printed program notebook

- Cover page with logo
- Inside page with illustration
- Letter from Ed
- High-level conference schedule - include QR code that links to Sessionize / EventMobi
   - [Schedule in Sessionize](https://f7fe99e3792b41578028010366ee0d55.sessionize.com/schedule)
   - [High-level Google calendar for conference](https://calendar.google.com/calendar/u/0?cid=Y19jMWNlNWQ3YmMzZmQzMjE0ZDBjNGE5ZWQxYTNkNzc2MTE5YTRjNzVjZmMxMjE0Y2RkZGIxYTBlZDgzZWQ5MzAzQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20)
- Conference venue map
   - [Link to map / venue info on drive](https://drive.google.com/drive/folders/1gxajDVmTaiBpaAyxjx43uTIKILZAK74o?usp=drive_link)
   - Should include restrooms, registration desk, EventMobi help desk, plenary and breakout rooms, etc.
- Sponsors - need vector logos for sponsors
   - [Folder with logo images](https://drive.google.com/drive/folders/1BKlBbpql0clkaLT_8W4YO5G2dPf0IYEJ) - 2 are missing (Schema & DRC)
   -  Order is based on sponsor tier - refer to sponsor prospectus and [tracking sheet](https://docs.google.com/spreadsheets/d/1AL_flaVrGCtNBdCr90rzzzUQAnf4aawRJk7vqKunru8/edit#gid=0)

What it will look like:

https://github.com/openedx/conference-planning-2024/assets/10086170/5755a4df-22a5-4068-8d83-2cb34c0abe41

**Comment by cassiezamparini** [comment]
@ehuthmacher and @mphilbrick211 Could you check the description above and let me know if all looks good? 😄

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini! Let me check in on this with Ed and get back to you.

Eden is traveling this week, so I'm not sure she'll see this until she returns.

**Comment by cassiezamparini** [comment]
> There will be a small program insert in the notebook as well.  How can I help? I can start a draft doc with possible content for the program insert if that would be helpful.

@mphilbrick211 this will be the program that we're talking about on this issue right? It would be great if we could confirm size, number of pages (outlined above) etc. So I'd really appreciate a draft document 😄

**Comment by mphilbrick211** [comment]
@cassiezamparini - yes, same one I mentioned on Slack. I'm also going to start an email chain with the two of us and Southern Cross so they can get you the specs ASAP.

I'll also get an outline to you.

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini! Please see [here](https://docs.google.com/document/d/1IHLrUMFPauPC5Fvf8xyycYQpDYO8rlA7r_mxpk_OZWk/edit) for an updated outline for the program. We won't be including the keynotes this time, but I think everything else stays.

I've requested drive access for you for items in the doc you may not have access to yet. I've also shared a high-level schedule layout that Feanil created on a google calendar. I believe some things are still being worked out for Friday, but at least we've got something in the meantime.

**Comment by cassiezamparini** [comment]
Just an update: the conference illustration and schedule are almost ready for review. I'll ping you all soon 😄 

@mphilbrick211 Last year Feanil generated a SVG QR code for that linked to the online program. Do you think he could help again?

**Comment by mphilbrick211** [comment]
@cassiezamparini I have some updated short blurbs for the special sessions for some quick add'l context for attendees (the big detail will live in EventMobi).

**Founders Lounge:** A chance for new and aspiring EdTech founders to connect with veteran founders and advisors. Includes a roundtable discussion, Q&A, and informal networking with resources from incubators, funders, and tech companies to provide insight on new ventures.

**Birds of a Feather:** Unstructured time where conference attendees propose topics they'd like to discuss, and other attendees "flock together" for meaningful conversation. Propose a topic, or peruse proposals on the sign-up sheet by the registration desk.

**Open edX Town Hall:** A chance to propose and discuss topics that pertain to the entire Open edX community. Open to all community members. Members of the Technical Oversight Committee (TOC) will be present to listen, answers questions and give their perspectives.

**Intro to Working Groups:** Each Open edX community Working Group will give a short presentation about the goals of the different working groups and how you can engage with them. There will be time afterwards to speak with working group representatives to ask more questions.

**Comment by mphilbrick211** [comment]
![Untitled](https://github.com/openedx/conference-planning-2024/assets/100873803/22593401-ba32-4d2d-b724-bdf491240c85)
> Just an update: the conference illustration and schedule are almost ready for review. I'll ping you all soon 😄
> 
> @mphilbrick211 Last year Feanil generated a SVG QR code for that linked to the online program. Do you think he could help again?

![Open edX Conf 2024](https://github.com/openedx/conference-planning-2024/assets/100873803/3bbb7863-6d83-4373-8666-d1cf2a4707b0)
[40360728.pdf](https://github.com/openedx/conference-planning-2024/files/15471135/40360728.pdf)
![Untitled](https://github.com/openedx/conference-planning-2024/assets/100873803/62f10386-30f4-449c-88fb-77201cd35f02)

@cassiezamparini

**Comment by mphilbrick211** [comment]
it's taking them to https://eventmobi.com/openedx2024 (confirmed by EventMobi).

CC: @parttechdev

**Comment by cassiezamparini** [comment]
@mphilbrick211 Will you ping me when the [spreadsheet](https://docs.google.com/spreadsheets/d/16MHuCfUaTPHCoTSTllFR8gejlt1W6DOOsGbYhheQOR8/edit#gid=0) is all filled out?

**Comment by mphilbrick211** [comment]
@cassiezamparini yes! Filling it out now. Will post here, along with some other quick updates this afternoon.

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini - here's the updates!

[Updated schedule and room list](https://docs.google.com/spreadsheets/d/16MHuCfUaTPHCoTSTllFR8gejlt1W6DOOsGbYhheQOR8/edit#gid=0) (with comments and notes). NOTE:

- We are looking into splitting the keynotes into one each day (instead of back to back). Will confirm this, for now, OK to keep as-is.
- I've added two items as placeholders on Friday ("Open edX Help Desk" and "Collaboration Corner" - we are still confirming these, and will have it to you ASAP.
- Zelda has updated the [map](https://www.canva.com/design/DAF-FM1rmEU/uTHjwp3NNwAxkhgwmvTlFA/view). NOTE that we are not going to utilize the 3rd floor room (3124), or the Schumann annex rooms.

Also, the hashtag for this year will be: #OpenEdx2024.

**Comment by cassiezamparini** [comment]
Awesome! Thank you @mphilbrick211 

I'll get on this and send you guys the printed program to review next week 😄

**Comment by cassiezamparini** [comment]
Hi @mphilbrick211 @e0d @ehuthmacher 

Could you review the program soonest? We need to sign off this design so we can start the rest of the collateral in the same vein. 

I've put together [this screencast](https://www.loom.com/share/15715b8fe30b4f9ea5db34515ab0ccaa?sid=c0b9af4a-59a0-4309-9e3e-4b6213a5ea33) explaining it all 😄 

Perhaps you can add comments directly to the PDF: [4.06 Printed Program Notebook.pdf](https://github.com/user-attachments/files/15552546/4.06.Printed.Program.Notebook.pdf)

**Comment by ehuthmacher** [comment]
@cassiezamparini It looks great to me! Thank you for all of your efforts! We do have a new Contributing sponsor, Intela. I am waiting for them to send their logo. When will you need it by?

**Comment by cassiezamparini** [comment]
Thanks @ehuthmacher 

If you could send it by Monday that would be ideal :)

**Comment by ehuthmacher** [comment]
@cassiezamparini Please find Intela's logo attached. Thank you! 
![Logo V1_White](https://github.com/openedx/conference-planning-2024/assets/79525573/b6dceaf5-857b-433d-b280-196556a5a364)

**Comment by ehuthmacher** [comment]
I added it to this drive as well: https://drive.google.com/drive/folders/1SMNgM5UvnDa3kkb_FdO-6cE681M4ZyQP

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini - here are some updates for the printed program (which looks amazing, btw):

**General**

- Please update the QR code language to: “Please use this QR code to view the full, comprehensive schedule on EventMobi. There you’ll find all event details, including sessions, room numbers, and speakers, along with general event information and updates.”
- Page 2: please update wifi working to: “Please see registration desk for Wi-Fi information.”
- Page 2: please update the recording disclaimer to read “All sessions will be recorded."
- Eden has provided the logo for the new [sponsor](https://github.com/openedx/conference-planning-2024/issues/72#issuecomment-2149590874) above.

**Map:**

- Please take out the sponsor table in the entrance across from registration - we no longer need it

**Schedule (note, these have been updated in the [sheet](https://docs.google.com/spreadsheets/d/16MHuCfUaTPHCoTSTllFR8gejlt1W6DOOsGbYhheQOR8/edit#gid=0)):**

**_For Wednesday’s Schedule:_** Updating the keynote title to say “Keynote: Hatim Eltayeb, CEO, African Leadership Academy, followed by “Building Bridges: Scaling Access to High-Quality Education" a roundtable discussion

**_For Thursday’s Schedule:_** Could you update it to say “Keynote: Prof. Jonathan Jansen, Stellenbosch University followed by The State of Open edX”

**_For Friday’s Schedule:_**
- Please remove both “Intro to Working Groups” and “Collaboration Corner” as they will no longer be happening
- Please update Open edX help desk to be from 10:00-11:30am (same time as the Founders Lounge) and a title change to “Open edX Office Hours” with the description of “Axim staff and community members will be on hand to help with your Open edX platform questions”
- Lunch time will now be 11:45am - 12:45pm

**Comment by cassiezamparini** [comment]
Just for our records - the latest proof: 
[7.06 Notebook.pdf](https://github.com/user-attachments/files/15740824/7.06.Notebook.pdf)

**Comment by ehuthmacher** [comment]
@cassiezamparini We have another sponsor, edSPIRIT. I added their logo to the shared drive and specified the level in the sponsor sheet. Let me know if you have any questions and thank you for the last minute addition!! FYI @mphilbrick211

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini - the newest draft looks great! A couple minor fixes below (and flagging Eden's new sponsor comment above):

Could we remove the "s" from "Keynotes" so it just says "Keynote and State of Open edX" ?
![Image](https://github.com/openedx/conference-planning-2024/assets/100873803/d3be6a15-566b-495b-bc94-3401ec7773a7)

The end of this blurb is missing - should read "Axim staff and community members will be on hand to help with your Open edX platform questions"
![Image](https://github.com/openedx/conference-planning-2024/assets/100873803/69094ec4-0643-4cf9-9edd-0cb4fc12a01d)

**Comment by cassiezamparini** [comment]
@mphilbrick211 One last look and then we can send it to print? 😄 let me know...

[10.06 Notebook Mock up.pdf](https://github.com/user-attachments/files/15765180/10.06.Notebook.Mock.up.pdf)

**Comment by mphilbrick211** [comment]
@cassiezamparini one more small change.

For Tuesday's schedule we're going to modify how the deep dive biz dev workshop is listed:
* Please remove "Part 1: Deep Dive Into the Open edX Platform's Competitive Standing & Future Enhancements" so that it only says "Afternoon Workshops" for that 1:30-3:30 slot
* For the 4:00-5:00 slot, we're going to keep the Deep Dive mention here, but change the wording to: "(continued from the 13:30 session) Deep Dive Into the Open edX Platform's Competitive Standing & Future Enhancements"


![Image](https://github.com/openedx/conference-planning-2024/assets/100873803/dcf40b2e-7dba-4f78-bd4e-464bd7b55f9a)

**Comment by cassiezamparini** [comment]
@mphilbrick211 Here is the latest version of the Notebook. Can you let me know if we can go to print 😄 

[12-06 A5 Program-Notebook.pdf](https://github.com/user-attachments/files/15805676/12-06.A5.Program-Notebook.pdf)

**Comment by mphilbrick211** [comment]
Thanks, @cassiezamparini - a few more small things and then I think this is all set. I've updated the [sheet](https://docs.google.com/spreadsheets/d/16MHuCfUaTPHCoTSTllFR8gejlt1W6DOOsGbYhheQOR8/edit#gid=0) to match.

**Wednesday:**

<img width="438" alt="image" src="https://github.com/openedx/conference-planning-2024/assets/100873803/9171c4c6-f068-4edc-931b-94d989351758">

* Please change the title to "Welcome and Plenary Sessions: Keynote and Roundtable" - the blurb can stay the same.
* Add a period at the end of the blurb.

<img width="420" alt="image" src="https://github.com/openedx/conference-planning-2024/assets/100873803/a37326e1-5431-414d-bd23-54cf51c1f436">

* Do we not have room to add the blurb to the BoF session on Weds? Ok if not, just checking.

**Thursday:**

<img width="442" alt="image" src="https://github.com/openedx/conference-planning-2024/assets/100873803/a2c2f7f4-d2a8-4f1d-90e2-2f4b77c6c9bd">

* Please change the title to "Plenary Sessions: Keynote and State of Open edX" 
* Remove the word "plenary" from the beginning of the blurb - otherwise, the blurb can stay the same.
* Add a period at the end of the blurb.

**Friday:**
* Add a period at the end of the "Office hours" blurb.

**Comment by cassiezamparini** [comment]
@mphilbrick211 See the final tweaks below 😄 

[Final Notebook.pdf](https://github.com/user-attachments/files/15809543/A5.Program-Notebook.pdf)

**Comment by mphilbrick211** [comment]
@cassiezamparini looks good! LGTM!

**Comment by cassiezamparini** [comment]
@mphilbrick211 Cool - Zelda has sent this to the printer! Here we go! 👯‍♀️
