### ISSUE TITLE
Speaker Photos and Bios for EventMobi

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/conference-planning-2024#75]
Confirm with EventMobi team if pulling from [here](https://sessionize.com/view/1n2ga1jt/GridSmart?format=Embed_Styled_Html&isDark=False&title=Open%20edX%20Conference%20-%202024) will suffice.

**Comment by mphilbrick211** [comment]
@davidw-sa @parttechdev - do you have everything you need for this? I know Feanil provided [this link](https://sessionize.com/api/v2/nv1gddu6/view/All) in the kick-off meeting. Please let us know if you need a different way to get this info. Thanks!

**Comment by parttechdev** [comment]
Hi, yes the sessionize link is perfect.
