### ISSUE TITLE
Sponsor Information for EventMobi

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/conference-planning-2024#76]
Add Sponsor logos and information to EventMobi shared folder: https://drive.google.com/drive/folders/1y1LtYYL2BEuldra1jGb3A7m4o9PSLdTW

**Comment by ehuthmacher** [comment]
Sponsor status is tracked [here ](https://docs.google.com/spreadsheets/d/1AL_flaVrGCtNBdCr90rzzzUQAnf4aawRJk7vqKunru8/edit#gid=0)and can be located on the conference website as well con.openedx.org (bottom of page). I have added the logos as separate files in the shared drive.
