### ISSUE TITLE
EventBrite information for EventMobi

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/conference-planning-2024#77]
Provide EventMobi team with Eventbrite info for integration into app.

**Comment by ehuthmacher** [comment]
@mphilbrick211 What information is needed for the integration?

**Comment by mphilbrick211** [comment]
> [@mphilbrick211](https://github.com/mphilbrick211) What information is needed for the integration?

@davidw-sa @parttechdev can you help with this?

**Comment by parttechdev** [comment]
Hi there, this article may help explain the process.

https://help.eventmobi.com/en/knowledge/eventbrite-1

We will need to add your eventbrite account manager to eventmobi as an organiser to complete the connection.

**Comment by ehuthmacher** [comment]
@parttechdev In order to complete the steps in the instructions, I will need to log in to EventMobi. Could you kindly provide me with such log in credentials and instructions?

**Comment by parttechdev** [comment]
Please provide your email so I can send through an organisation invite.

**Comment by ehuthmacher** [comment]
@parttechdev It is ehuthmacher@axim.org

**Comment by parttechdev** [comment]
You should have received an email from noreply@eventmobi.com.

**Comment by parttechdev** [comment]
![image](https://github.com/openedx/conference-planning-2024/assets/168561467/75538cac-c92b-4348-93f9-a1097f3274b9)

**Comment by ehuthmacher** [comment]
@parttechdev I created an av=ccount. However, under the "integrations" tab, there is no option for Eventbrite. See screenshot: 
<img width="1512" alt="Screen Shot 2024-05-07 at 8 44 15 AM" src="https://github.com/openedx/conference-planning-2024/assets/79525573/b552c066-65df-4546-817a-4ab6830b0a33">

**Comment by parttechdev** [comment]
Navigate to the `Events` tab.
Click the Open edX event.
On the left hand menu you will see `Integrations.`

**Comment by ehuthmacher** [comment]
@parttechdev I see the option and I am clicking on it, but there is no option for Eventbrite. See screenshot; 
<img width="1512" alt="Screen Shot 2024-05-07 at 8 55 42 AM" src="https://github.com/openedx/conference-planning-2024/assets/79525573/62ed484b-7a6a-4b14-afab-ab33056edcd1">

**Comment by parttechdev** [comment]
Please click `Events`
![image](https://github.com/openedx/conference-planning-2024/assets/168561467/54bf5d0e-66f0-4df4-a3b3-ca128de010cc)

Then click `Open edX Conference 2024`
![image](https://github.com/openedx/conference-planning-2024/assets/168561467/afe3f53a-0360-416b-b621-0784bbe0a04b)

Then you will have `Integrations` towards to bottom of the menu.
![image](https://github.com/openedx/conference-planning-2024/assets/168561467/6bffcdaf-e038-4e64-8274-0f5543196b72)

**Comment by ehuthmacher** [comment]
Thank you @parttechdev , I found it. However another issue occured, the correct event is not displaying in the drop down menu and when I add it manually, it states that there is no data to display. See screenshot: 
<img width="1512" alt="Screen Shot 2024-05-07 at 9 34 41 AM" src="https://github.com/openedx/conference-planning-2024/assets/79525573/47e93fc4-acba-402d-986b-268e85e47869">

**Comment by parttechdev** [comment]
What is the full name of the event on Eventbrite?

**Comment by ehuthmacher** [comment]
@parttechdev It is Open edX Conference 2024

**Comment by parttechdev** [comment]
Thanks, not seeing it on my end either. Are you an admin for that specific event?

**Comment by ehuthmacher** [comment]
@parttechdev Yes, I am an admin.
