### ISSUE TITLE
Founders Lounge Site Page

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/conference-planning-2024#80]
Hi @cassiezamparini! @e0d has put together a session called the "Founders Lounge" taking place on the Friday of the conference from 10-11:30.

He's gathered an awesome group of people to take part in this, and we're hoping we can create a new page off the main conference website to highlight it, and use that page to promote it on social, etc.

We'd love it if you could do this in the same style that you did with the keynotes on the main page.

Ed is in the process of securing formal bios and photos for everyone, but I've put the detail we currently have below. As we get the bios and everything, we'll stick them in [this folder](https://drive.google.com/drive/folders/1Y8ugMDSfAPHi676cUlqtrBtTyUvrIlw1?usp=drive_link) for you.

Let us know if you have any questions in the meantime.

_

> The Founders Lounge is a new event at the Open edX conference that will bring together veteran EdTech founders from a variety of backgrounds to connect with new and aspiring founders.
> 
> The focus will be educational technology, and the content will be relevant whether you are hoping to start a mission driven non-profit or startup.
> 
> We’ll start with a roundtable discussion and insights into the process of getting from a kernel of an idea, to a business plan, to a going concern. We’ll then have time for audience Q&A and informal networking.
> 
> This will be a great opportunity to connect with and learn from founders who have done it before, sometimes more than once.
> 
> Also in attendance will be resources from incubators, funders, and technology companies who provide insights, advice and resources to help catalyze new ventures.

_

The five people on the panel will be:
[Naadiya Moosajee](https://www.womhub.com/our-executive-team.html#:~:text=through%20her%20work.-,Naadiya%20Moosajee,-Co%2Dfounder%20%26%20CIO)
[Kagisho Masae](https://200youngsouthafricans.co.za/kagisho-masae-34-2022/)
[Hannes Gldenhuys](https://www.noodle.com/team/hannes-geldenhuys/)
[Carl Dawson](https://www.bsg.ox.ac.uk/people/carl-dawson)
[Tsepo Ngwenyama](https://za.linkedin.com/in/tsepongwenyama)

**Comment by cassiezamparini** [comment]
@mphilbrick211 Perfect! I'll get to this asap.

**Comment by e0d** [comment]
I've added the assets I have to the folder and have followed up with the other folks.

https://drive.google.com/drive/folders/1Y8ugMDSfAPHi676cUlqtrBtTyUvrIlw1

**Comment by cassiezamparini** [comment]
Thanks @e0d. This is basically ready to go when we get all the pics and bios.

**Comment by cassiezamparini** [comment]
@e0d and @mphilbrick211 [Here's a link](https://con.openedx.org/?page_id=1187&preview_id=1187&preview_nonce=a34f117576&preview=true) to the page in preview mode (you'll need to be logged in to see it). Let me know your thoughts 😄 

We just need Tsepo's details and then we're set.

I thought I could add a section to the main landing page that links people to the Founders page - rather than including it in the main nav. Just so the UX is consistent in the main nav and we don't add another item.

**Comment by e0d** [comment]
Overall, looks great.  Very excited.  I've reached back out to Tsepo today.

I published the page and made it password protected.  Not everyone had an account there.  I think we should add a sentence about the schedule and a CTA for folks.  Where to get tickets, how to reach out if there are questions.

**Comment by mphilbrick211** [comment]
@cassiezamparini this looks great! In addition to Ed's comment above, we'd like to slightly re-word Kagisho's bio to include his name and make it a bit more personal. Could you update it as follows?:

Kagisho is the Co-founder & CEO of Matric Live, a learning platform that has cumulatively given access to over 1 million South African learners from 2020 – present. He is a finance professional & client experience enthusiast with experience in finance, customer service, partner relations, loyalty & rewards programs, project management, digital marketing & EdTech. Kagisho was recognized as one of the Mail & Guardian Top 200 Young South Africans in 2022. He is also a One Young World Ambassador, passionate about giving back & the empowerment of the previously disadvantaged.

**Comment by e0d** [comment]
@cassiezamparini I've added Tsepo's details.  @mphilbrick211 the bio is comparatively long.

**Comment by mphilbrick211** [comment]
Hi @cassiezamparini - let us know if you have any questions on the above!

**Comment by cassiezamparini** [comment]
@e0d @mphilbrick211 Will you take a look again 😄 [Here's the link](https://con.openedx.org/?page_id=1187&preview_id=1187&preview_nonce=a34f117576&preview=true)

If all looks good I'll add a section to the landing page that links to the Founders page. Where on the landing page would you like me to advertise this? Below/above which section? https://con.openedx.org

**Comment by mphilbrick211** [comment]
@cassiezamparini - looks great! Is there a way to add a bit more of Tsepo's bio? I know it was long, but I think the bios above Tespo's are larger as well.

As far as on the main page, I think putting this in the schedule section, maybe under the schedule, that says "Be sure to check out our new Founder's Lounge session on Friday!" - So not necessarily it's own heading, but something under the schedule that highlights it.

**Comment by cassiezamparini** [comment]
@mphilbrick211 All updated, and it's now live 😄 if there are any other tweaks I can make them for you on Monday. But at least this is good to go.

The only thing I need development help with is making sure the navigation at the top of the Founders page goes back to the landing page. Alternatively, maybe we lose the navigation on this page, and just have the logo and a link that says "back". 

Let me know your thoughts - the UX is a bit weird as all the menu items are for one page and this is now a separate page.

**Comment by mphilbrick211** [comment]
Thanks, @cassiezamparini! Looks great!

The Founders Page doesn't go back to the main page - the top nav doesn't work from the Founders page. If I click the browser's back arrow it does, but not from the site's nav.

CC: @e0d

**Comment by cassiezamparini** [comment]
@mphilbrick211 

> The Founders Page doesn't go back to the main page - the top nav doesn't work from the Founders page. If I click the browser's back arrow it does, but not from the site's nav.

Yes, it's weird, this is what I need dev help with. See what I said here and let me know your thoughts:

> The only thing I need development help with is making sure the navigation at the top of the Founders page goes back to the landing page. Alternatively, maybe we lose the navigation on this page, and just have the logo and a link that says "back".
> 
> Let me know your thoughts - the UX is a bit weird as all the menu items are for one page and this is now a separate page.

**Comment by amirnafees88** [comment]
@cassiezamparini I am looking into this issue.

**Comment by amirnafees88** [comment]
@cassiezamparini Issue resolved. Now you can go to the homepage and scroll to a particular section by clicking from the top navigation menu items.

CC: @e0d

**Comment by mphilbrick211** [comment]
Looks great! Thanks @amirnafees88 and @cassiezamparini!

**Comment by cassiezamparini** [comment]
Amazing @amirnafees88! Thank you 😄 

@mphilbrick211 Are you happy if we close the ticket?

**Comment by e0d** [comment]
If possible, could we look at figuring out what we need to do to make images look good on LinkedIN?

![image](https://github.com/openedx/conference-planning-2024/assets/1270274/d2f11631-be32-426f-bc34-48d1dbdfe222)

**Comment by cassiezamparini** [comment]
@amirnafees88 can you let me know how to update the Linkedin preview image shown? I added feature images to the website pages, but they're not displaying on the Linkedin previews... perhaps I'm missing something 😄

**Comment by amirnafees88** [comment]
@cassiezamparini We are looking into it.

**Comment by cassiezamparini** [comment]
@amirnafees88 Any luck with the sharing image?

**Comment by amirnafees88** [comment]
@cassiezamparini I added the image in yoast social setting and then clear website cache and then preview in LinkedIn post and its working now. You have to post again in LinkedIn. Screenshots attached for reference.

<img width="1742" alt="Screenshot 2024-05-15 at 2 24 08 PM" src="https://github.com/openedx/conference-planning-2024/assets/93266196/67f02ecb-eac2-4fc7-9777-f7ab49fec0c8">
<img width="751" alt="Screenshot 2024-05-15 at 2 23 10 PM" src="https://github.com/openedx/conference-planning-2024/assets/93266196/3d43e58b-1ba2-4fc7-af72-d832baa7ea7b">


CC: @e0d @awais-ansari

**Comment by cassiezamparini** [comment]
Amazing! It's working! Thank you.

@e0d can you check too? And then close this issue if all is well?

**Comment by e0d** [comment]
Is this something that will work for future posts automatically or do we need do the Yoast step for each post?

**Comment by amirnafees88** [comment]
@e0d If you want to change the feature image of a page then you have to modify the image in Yoast social settings and clear site cache. Otherwise it is not required.
