### ISSUE TITLE
Conference Design Items

### ISSUE THREAD

**Issue by cassiezamparini** [openedx/conference-planning-2024#82]
### Printed program notebook

The following items need to be designed by OpenCraft in the style of https://github.com/openedx/conference-planning-2024/issues/72:

- [ ] 1 x [2.4m Dolphin Flag.pdf](https://github.com/user-attachments/files/15552673/2.4m.Dolphin.Flag.pdf) design (will be printed multiple times)
- [ ] +/- 15 x XBanners - directional aids - 800x1800mm with a 5mm bleed all around with crop marks. Include a banner with a QR code
- [ ] Name tags - 90 X 105mm (portrait)
![81d56071-7ccc-4905-8072-20ba0d323740](https://github.com/openedx/conference-planning-2024/assets/10086170/2410215f-a101-4cd3-9476-a20814862e06)

![a60effe6-58df-47cd-aed6-f8e7b48ca4db](https://github.com/openedx/conference-planning-2024/assets/10086170/dec9d1c0-1034-473d-a830-da7d5d8a613f)

**Comment by cassiezamparini** [comment]
@mphilbrick211 @ehuthmacher Okay, now that the program is under review, I'd like to get my head around what else we need to do...

I've referenced [this spreadsheet](https://docs.google.com/spreadsheets/d/1vo1iLmUPGOQ6aHvel-tg0PYHdSdAyvzcKMxrwMh6aBI/edit#gid=0) for the description above. Some questions:

-  I see Zelda has indicated that the directional signs etc will be X-banners this year?
- Can you look through the [XBanners - directional aids.pdf](https://github.com/user-attachments/files/15560215/XBanners.-.directional.aids.pdf) mockups and confirm if those are all the banners we need to design? I see there is a lecture room 3124 and two Schumann ones - which we don't need.
- Should the schedule QR code be a poster or Xbanner?
- Do you have the certificate details yet?
- Are we doing stickers this year?
- And are the name tag specs the same as last year? Will you be doing them in the US again?

**Comment by mphilbrick211** [comment]
@cassiezamparini 

- I will leave the banner questions to Zelda
- I would do the QR code as a poster that we can have by registration, but I'd also confirm with Zelda on what she thinks is best.
- @ehuthmacher are we doing certs this year?
- Yes, we're doing stickers, but those are all set. Zelda has the logo files you did for us and is having them printed locally by MinuteMan Press.
- Name tags will be done locally as well. I'm not sure abut the design. This may be another question for Zelda. I'm guessing we'd do simple, with one of the custom logos and a similar setup as we've done in the past.

**Comment by ehuthmacher** [comment]
@mphilbrick211 Do you mean the CC certs? If so, then no we are not.

**Comment by mphilbrick211** [comment]
> @mphilbrick211 Do you mean the CC certs? If so, then no we are not.

Yes, the working group awards.

Ok @cassiezamparini - no certificates this year.

**Comment by ehuthmacher** [comment]
@mphilbrick211 We are not having an award ceremony this year.

**Comment by mphilbrick211** [comment]
@cassiezamparini no pronoun stickers this year - people have the ability to add it in EventBrite when they get tickets (though no one has actually filled that in yet).

**Comment by cassiezamparini** [comment]
@mphilbrick211 Here are the proofs for the Badge and Dolphin flag. Let me know what you all think 😄 

Dolphin flag:
<img width="294" alt="7 06 Dolphin flag proof" src="https://github.com/openedx/conference-planning-2024/assets/10086170/0efd122b-ebb0-4e71-8593-2180dcb83953">

Badge:
<img width="400" alt="7 06 Badge Proof" src="https://github.com/openedx/conference-planning-2024/assets/10086170/c65b60f7-0682-42ab-a196-efe7eb1d13a4">


Example of a printed badge from the printer we are using:
![fa58bee5-c307-4a31-a073-bf6f775b70e7](https://github.com/openedx/conference-planning-2024/assets/10086170/deaec55f-9dd0-4e9f-81e4-1e299e0d945a)

**Comment by cassiezamparini** [comment]
Hi @mphilbrick211 

Here are the Xbanners for review 😄 

[XBanners - Open edX 2024.pdf](https://github.com/user-attachments/files/15805627/XBanners.-.Open.edX.2024.pdf)

And the updated badge at 115mm x 75mm:

<img width="500" alt="Screenshot 2024-06-12 at 15 29 25" src="https://github.com/openedx/conference-planning-2024/assets/10086170/bf600f85-ca07-4fab-a50e-159e38485302">

**Comment by mphilbrick211** [comment]
@cassiezamparini banners look great! Had a couple pieces of feedback I also put in [Slack](https://openedx.slack.com/archives/C074ZE22TLH/p1718199610556309?thread_ts=1718198069.741429&cid=C074ZE22TLH).

* The sponsor logos are OK, correct? Last year I remember we scrambled a bit becuase some of them weren't the correct resolution for the large banners. If we need to get you updated files, please let me know!
* Zelda suggested adding the wine barrel to all the signs (like you did to the "Welcome" sign)
<img width="403" alt="Screenshot 2024-06-12 at 9 39 43 AM" src="https://github.com/openedx/conference-planning-2024/assets/100873803/f7bb81ec-bef3-45d6-b40f-b52c05e8fb07">

**Comment by mphilbrick211** [comment]
@cassiezamparini badges look great!

**Comment by cassiezamparini** [comment]
@mphilbrick211 

1. Great - I'll add the badges to the design folder Zelda created. 

2. For the Xbanners, you make a good point, I've double checked and they seem "okay" but I would prefer vector logos for:
   - Axim
   - Construct
   - Intela
   - IBL

Do you think we could get the logos by Friday? Everything needs to go into print by Monday

**Comment by ehuthmacher** [comment]
@cassiezamparini I have requested those for you and will let you know if I receive them before Fri.

**Comment by ehuthmacher** [comment]
For Axim, we only have the current version or the attached pdf file
[axim-collaborative-logo-black-cmyk.pdf](https://github.com/user-attachments/files/15810328/axim-collaborative-logo-black-cmyk.pdf)

**Comment by ehuthmacher** [comment]
IBL attached
![ibllogo-transparent](https://github.com/openedx/conference-planning-2024/assets/79525573/d8062e58-6992-4580-954c-e9f2b2a471f9)

**Comment by ehuthmacher** [comment]
I added both to the drive: https://drive.google.com/drive/folders/1SMNgM5UvnDa3kkb_FdO-6cE681M4ZyQP

**Comment by cassiezamparini** [comment]
@ehuthmacher and @mphilbrick211 

The Axim logo is a vector and perfect, but it doesn't include the word "Collaborative" - is that fine to use? I can keep it as is in the program.

![Screenshot 2024-06-13 at 14 50 23](https://github.com/openedx/conference-planning-2024/assets/10086170/b212f006-7fa1-46c5-bf31-65e2696323f9)

**Comment by ehuthmacher** [comment]
@cassiezamparini Yes, that is fine. You can use the Axim logo as is. Thank you for checking.
